name: build-and-test

on:
  push:
    branches:
      - master
    tags:
      - "v*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "*"
    tags:
      - "*"
    paths-ignore:
      - "**.md"

jobs:
  multi-os:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout to committer
        uses: actions/checkout@v2

      - name: Pre-build steps
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ];  then sudo apt-get install -y libssl-dev; fi
          if [ "${{ matrix.os }}" = "macos-latest" ];   then gem install bundler;  fi
          if [ "${{ matrix.os }}" = "macos-latest" ];   then brew install openssl; fi
          if [ "${{ matrix.os }}" = "windows-latest" ]; then choco install curl; fi

      - name: Environment info
        run: echo $GITHUB_SHA $GITHUB_REF

      - name: Add V download dir to PATH
        run: echo "/tmp/v" >> $GITHUB_PATH

      - name: Install V
        run: bash "${GITHUB_WORKSPACE}/.github/install-v.sh"
        env:
          OS: "${{ matrix.os }}"

      - name: Compile committer
        run: make

      - name: Configure git
        run: |
          git config --global user.email "hi@caian.org"
          git config --global user.name "Caian R. Ertl"

      - name: See info
        run: |
          ./committer -h
          ./committer -v

      - name: Execute in loop
        run: |
          # run a couple of times as a "stress test"
          for i in $(seq 1 50); do ./committer; done

      - name: Rename artifact
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            export ARTIFACT="committer-${GITHUB_SHA}-linux"
          fi

          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            export ARTIFACT="committer-${GITHUB_SHA}-macos"
          fi

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            export ARTIFACT="committer-${GITHUB_SHA}-windows.exe"
          fi

          mv committer "$ARTIFACT"

          ls -lash
          echo "::set-env name=ARTIFACT::${ARTIFACT}"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "${{ env.ARTIFACT }}"
          path: "${{ env.ARTIFACT }}"
          retention-days: 1
